preload = /home/miko/Pictures/Meant to be Wallpaper/RandySouthPark.jpg

wallpaper {
    monitor = HDMI-A-2
    path = /home/miko/Pictures/Meant to be Wallpaper/RandySouthPark.jpg
    fit_mode = cover
}

splash = false
