preload = /home/miko/Pictures/Meant to be Wallpaper/anime-girl-flowting-in-pool.jpg

wallpaper {
    monitor = HDMI-A-2
    path = /home/miko/Pictures/Meant to be Wallpaper/anime-girl-flowting-in-pool.jpg
    fit_mode = cover
}

splash = false
